services:
  api:
    build:
      context: ./services/
    env_file:
      - ./.env
    environment:
      - SQLITE_PATH=${SQLITE_PATH}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - sqlite_data:/data
    expose:
      - "${API_PORT}"
    restart: unless-stopped

  web:
    build:
      context: ./client
      args:
        - VITE_API_BASE=${VITE_API_BASE}
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  sqlite_data:
